version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: echo-rest-api-db
    restart: always
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      - lesson
volumes:
  mysql-data:
    driver: local
networks:
  lesson:
